import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a professional PDF security report for the scan results.
 * @param {Array} results - The scan results array from App.js state.
 * @param {Object} stats - The statistics object (total, critical, score).
 */
export const generatePDFReport = (results, stats) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();
  
  // PDF Branding Colors
  const colors = {
    primary: [220, 38, 38], // Red-600
    dark: [15, 23, 42],     // Slate-900
    gray: [100, 116, 139],  // Slate-500
    critical: [185, 28, 28], // Red-700
    high: [194, 65, 12],    // Orange-700
    medium: [180, 83, 9],   // Amber-700
    low: [51, 65, 85]       // Slate-700
  };

  // 1. Header
  doc.setFillColor(...colors.primary);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('JSentinel Security Report', 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${timestamp}`, 14, 30);
  doc.text('Local-First Browser Static Analysis', 140, 30);

  // 2. Summary Section
  doc.setTextColor(...colors.dark);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 14, 55);

  autoTable(doc, {
    startY: 60,
    head: [['Metric', 'Value']],
    body: [
      ['Security Score', `${stats.securityScore}%`],
      ['Total Files Scanned', results.length],
      ['Total Vulnerabilities Found', stats.totalIssues],
      ['Critical Vulnerabilities', stats.criticalIssues]
    ],
    theme: 'striped',
    headStyles: { fillStyle: 'zinc', fillColor: [51, 65, 85] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 80 },
      1: { halign: 'right' }
    }
  });

  let currentY = doc.lastAutoTable.finalY + 20;

  // 3. Detailed Findings
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Findings', 14, currentY);
  currentY += 10;

  const filesWithIssues = results.filter(r => r.issues && r.issues.length > 0);

  if (filesWithIssues.length === 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...colors.gray);
    doc.text('No security vulnerabilities were detected during this scan.', 14, currentY);
  } else {
    filesWithIssues.forEach((fileResult, index) => {
      // Check for page break before adding a new file section
      if (currentY > 250) {
        doc.addPage();
        currentY = 20;
      }

      doc.setFontSize(12);
      doc.setTextColor(...colors.primary);
      doc.setFont('helvetica', 'bold');
      doc.text(`File: ${fileResult.fileName}`, 14, currentY);
      currentY += 5;

      const tableData = [...fileResult.issues]
        .sort((a, b) => {
          const priority = { 'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3 };
          return (priority[a.severity] ?? 99) - (priority[b.severity] ?? 99);
        })
        .map(issue => [
          issue.severity,
          issue.id,
          `Line ${issue.line}`,
          `${issue.message}\n\nSuggestion: ${issue.suggestion}`
        ]);

      autoTable(doc, {
        startY: currentY,
        head: [['Severity', 'Rule ID', 'Location', 'Finding & Suggestion']],
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [51, 65, 85] },
        didParseCell: (data) => {
          if (data.section === 'body' && data.column.index === 0) {
            const severity = data.cell.raw;
            if (severity === 'CRITICAL') data.cell.styles.textColor = colors.critical;
            if (severity === 'HIGH') data.cell.styles.textColor = colors.high;
            if (severity === 'MEDIUM') data.cell.styles.textColor = colors.medium;
            data.cell.styles.fontStyle = 'bold';
          }
        },
        columnStyles: {
          0: { cellWidth: 20 },
          1: { cellWidth: 25 },
          2: { cellWidth: 20 },
          3: { cellWidth: 'auto' }
        }
      });

      currentY = doc.lastAutoTable.finalY + 15;
    });
  }

  // 4. Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...colors.gray);
    doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
    doc.text('Confidential Security Report - Generated by JSentinel', 14, 285);
  }

  doc.save(`JSentinel-Report-${new Date().toISOString().split('T')[0]}.pdf`);
};
